#!/usr/bin/perl -w

use strict;
use LWP::UserAgent;
use HTTP::Request::Common;

$ENV{'SPROUT_MODEL_IN'} = '/home/ubuntu/PA3/alfalfa/src/examples/sprout.model';

my $receiver_pid = fork;

if ( $receiver_pid < 0 ) {
  die qq{$!};
} elsif ( $receiver_pid == 0 ) {
  # child
  exec q{/home/ubuntu/PA3/alfalfa/src/examples/sproutbt2} or die qq{$!};
}

chomp( my $prefix = qx{dirname `which mm-link`} );
my $tracedir = $prefix . q{/../share/mahimahi/traces};

# run the sender inside a linkshell and a delayshell
my @command = qw{mm-delay 20 mm-link UPLINK DOWNLINK};

# display livegraphs if we seem to be running under X
if ( defined $ENV{ 'DISPLAY' } ) {
    push @command, qw{--meter-uplink --meter-uplink-delay};
}

push @command, qw{ --uplink-queue=red --downlink-queue=red --uplink-queue-args=min_bytes=375000max_bytes=1125000drop_percentage=10 --downlink-queue-args=min_bytes=375000max_bytes=1125000drop_percentage=10 --once --uplink-log=/home/ubuntu/PA3/logs/sprout_alma_short_log -- sh -c};

push @command, q{/home/ubuntu/PA3/alfalfa/src/examples/sproutbt2 $MAHIMAHI_BASE 60001};

# for the contest, we will send data over Verizon's downlink
# (datagrump sender's uplink)
die unless $command[ 3 ] eq "UPLINK";
$command[ 3 ] = qq{$tracedir/TMobile-LTE-short.down};

die unless $command[ 4 ] eq "DOWNLINK";
$command[ 4 ] = qq{$tracedir/TMobile-LTE-short.up};

system @command;

# kill the receiver
kill 'INT', $receiver_pid;

print "\n";

# analyze performance locally
system q{mm-throughput-graph 500 /home/ubuntu/PA3/logs/sprout_alma_short_log > /dev/null};

print "\n";

# gzip logfile
# print q{Uploading data to server...};

# my $www = LWP::UserAgent->new();
# my $request = POST 'http://cs344g.keithw.org/cgi-bin/6829/upload-data',
#  Content_Type => 'multipart/form-data',
#  Content => [contents => ['/tmp/contest_uplink_log', $username]];

# my $response = $www->request( $request );

# print qq{ done.\n\n};

# print $response->decoded_content;

# print "\n";
